### ISSUE TITLE
Can't Parse Sample Route

### ISSUE THREAD

**Issue by jsl303** [appscape/gips#1]
$ gips.rb --speed 5 vienna-ring-bikeride.gpx test.gpx
Found 0 route points in vienna-ring-bikeride.gpx.
Wrote 0 points to test.gpx to simulate speed of 5 km/h.

**Comment by roobytwo** [comment]
@jsl303 can you share the gpx file?

**Comment by nitishmakhija** [comment]
Same issue as of @jsl303

**Comment by esad** [comment]
Should be fixed by @michaelochs PR. Note that sample routes were already meant for consumption by simulator, but now you should be able to change the speed on those too.
